### ISSUE TITLE
Metroid Rogue Dawn patch crashing ips softpacher in nestopia

### ISSUE THREAD

**Issue by i30817** [libretro/nestopia#44]
Appending --no-patch to the cmd line makes it start and proves the patch is the problem. CRC32 of the rom here matches required crc for the rom.

You can find the patch here:
http://www.romhacking.net/hacks/3280/

Backtrace. I installed the retroarch-dbg package but it doesn't seem to have helped. Maybe it's not on the ppa and i'm using the wrong one?
https://gist.github.com/i30817/35cb0c0de438d32b7467c4431250ec1e

**Comment by i30817** [comment]
And of course, if the rom is hardpatched, it works... so something is buggy.

**Comment by rdanbrook** [comment]
This is probably an issue related to RetroArch handling patches, despite Nestopia wanting to handle patches itself. I'll look deeper into it soon.

The hack is pretty cool, I played it for a bit in the standalone.

**Comment by i30817** [comment]
BTW meanwhile RA somehow acquired another bug that is causing --no-patch to have no effect.
https://github.com/libretro/RetroArch/issues/4527

I can tell it was introduced between reporting this issue and that one because i tried to run the metroid rom here with --no-patch and it worked and when i try now, it always crashes.

This is besides another bug about softpatching not working 'by design' on certain cores. Seems like softpatching in RA is cursed.

**Comment by rdanbrook** [comment]
I'm gonna close this because the real issue is a frontend issue, which I'm not sure has been resolved or not.

**Comment by retro-wertz** [comment]
as i was trying to support soft-patching in fceumm_libretro, i learned that
using fullpath=false(just like with nestopia) will instruct retroarch to
load content/patch using its own routine.

you should probably start using "fullpath=true" then if nestopia was
suppose to load patches on its own(which as i was testing in linux compiled
with cmake still does not load ips patches with mapper 23)

**Comment by fr500** [comment]
fullpath true has it's own set of problems though....
for netplay content matching.

We should always strive for fullpath = false.
